#### RNNs Pytorch Examples

This notebook contains examples using some RNNs implementations available in Pytorch.

1.  LSTMCell vs LSTM (GPU Support)

In [1]:
import torch.nn as nn
import torch

torch.manual_seed(12)

# features 10, hidden size 20
rnn = nn.LSTMCell(10, 20)
# (time_steps, batch, input_size)
input = torch.randn(2, 3, 10)
# (batch, hidden_size)
hx = torch.randn(3, 20)
# (batch, hidden_size)
cx = torch.randn(3, 20)
# list to save outputs each time step
output = []
for i in range(input.size()[0]):
        print(f" step {i} , Input : {input[i].shape}")
        print(f" step {i} , hidden state : {hx.shape}")
        print(f" step {i} , cell state : {cx.shape}")

        hx, cx = rnn(input[i], (hx, cx))
        output.append(hx)       

output  = torch.stack(output, dim = 0)

print(f" \n Output LSTMCell: {output.shape}")
print(f" \n Output LSTMCell:\n {output}")

 step 0 , Input : torch.Size([3, 10])
 step 0 , hidden state : torch.Size([3, 20])
 step 0 , cell state : torch.Size([3, 20])
 step 1 , Input : torch.Size([3, 10])
 step 1 , hidden state : torch.Size([3, 20])
 step 1 , cell state : torch.Size([3, 20])
 
 Output LSTMCell: torch.Size([2, 3, 20])
 
 Output LSTMCell:
 tensor([[[ 0.2552, -0.1090, -0.0835,  0.2958, -0.4213, -0.0170,  0.2474,
           0.1677, -0.3955, -0.1091,  0.2386, -0.0052,  0.3028,  0.2637,
           0.0113, -0.3665, -0.0687, -0.0280, -0.3560,  0.0247],
         [-0.0958, -0.0987,  0.3122, -0.1819, -0.0390, -0.3634,  0.1293,
           0.2141, -0.5724, -0.1846, -0.3133, -0.1564, -0.0349,  0.2602,
           0.3982, -0.3867,  0.3485,  0.0338, -0.2344,  0.0718],
         [-0.1596,  0.0429,  0.3663, -0.0377,  0.1968, -0.2228, -0.0025,
          -0.0077, -0.1359,  0.0810,  0.1197, -0.0336,  0.0129, -0.1988,
          -0.2814,  0.2207, -0.0302, -0.1498, -0.3188, -0.0169]],

        [[ 0.1216, -0.0640, -0.1142, -0.1368, -0.

In [2]:
torch.manual_seed(12)

# (input_size, hidden_size, layers)
rnn = nn.LSTM(10, 20, 1)
# (seq_len, batch, input_size)
input = torch.randn(2, 3, 10)
# (num_layers, batch, hidden_size)
h0 = torch.randn(1, 3, 20)
c0 = torch.randn(1, 3, 20)
output, (hn, cn) = rnn(input, (h0, c0))

print(f" \n Output : {output.shape}")
print(f" \n hidden state : {hn.shape}")
print(f" \n cell state : {cn.shape}")
print(f" \n Output LSTM:\n {output}")


 
 Output : torch.Size([2, 3, 20])
 
 hidden state : torch.Size([1, 3, 20])
 
 cell state : torch.Size([1, 3, 20])
 
 Output LSTM:
 tensor([[[ 0.2552, -0.1090, -0.0835,  0.2958, -0.4213, -0.0170,  0.2474,
           0.1677, -0.3955, -0.1091,  0.2386, -0.0052,  0.3028,  0.2637,
           0.0113, -0.3665, -0.0687, -0.0280, -0.3560,  0.0247],
         [-0.0958, -0.0987,  0.3122, -0.1819, -0.0390, -0.3634,  0.1293,
           0.2141, -0.5724, -0.1846, -0.3133, -0.1564, -0.0349,  0.2602,
           0.3982, -0.3867,  0.3485,  0.0338, -0.2344,  0.0718],
         [-0.1596,  0.0429,  0.3663, -0.0377,  0.1968, -0.2228, -0.0025,
          -0.0077, -0.1359,  0.0810,  0.1197, -0.0336,  0.0129, -0.1988,
          -0.2814,  0.2207, -0.0302, -0.1498, -0.3188, -0.0169]],

        [[ 0.1216, -0.0640, -0.1142, -0.1368, -0.2694, -0.1684,  0.1206,
           0.1096, -0.2894, -0.0532,  0.1241,  0.0037,  0.0609,  0.0435,
          -0.0029,  0.0019, -0.0049, -0.0011, -0.2284, -0.0170],
         [-0.1441,  0.

2. Using LSTM like an LSTMCell (loop through time)

In [3]:
torch.manual_seed(12)

# (input_size, hidden_size, layers)
rnn = nn.LSTM(10, 20, 1)
# (seq_len, batch, input_size)
input = torch.randn(2, 3, 10)
# (num_layers, batch, hidden_size)
hx = torch.randn(1, 3, 20)
cx = torch.randn(1, 3, 20)

outputs = []
for i in range(input.shape[0]):
    
        print(f" \n step {i} , Input : {input[i:i+1,:,:].shape}")
        print(f" step {i} , hidden state : {hx.shape}")
        print(f" step {i} , cell state : {cx.shape}")

        output, (hx, cx) = rnn(input[i:i+1,:,:], (hx, cx))
        outputs.append(output)
        
outputs  = torch.stack(outputs, dim = 0)
print(f" \n Output LSTM: \n {outputs}")

 
 step 0 , Input : torch.Size([1, 3, 10])
 step 0 , hidden state : torch.Size([1, 3, 20])
 step 0 , cell state : torch.Size([1, 3, 20])
 
 step 1 , Input : torch.Size([1, 3, 10])
 step 1 , hidden state : torch.Size([1, 3, 20])
 step 1 , cell state : torch.Size([1, 3, 20])
 
 Output LSTM: 
 tensor([[[[ 0.2552, -0.1090, -0.0835,  0.2958, -0.4213, -0.0170,  0.2474,
            0.1677, -0.3955, -0.1091,  0.2386, -0.0052,  0.3028,  0.2637,
            0.0113, -0.3665, -0.0687, -0.0280, -0.3560,  0.0247],
          [-0.0958, -0.0987,  0.3122, -0.1819, -0.0390, -0.3634,  0.1293,
            0.2141, -0.5724, -0.1846, -0.3133, -0.1564, -0.0349,  0.2602,
            0.3982, -0.3867,  0.3485,  0.0338, -0.2344,  0.0718],
          [-0.1596,  0.0429,  0.3663, -0.0377,  0.1968, -0.2228, -0.0025,
           -0.0077, -0.1359,  0.0810,  0.1197, -0.0336,  0.0129, -0.1988,
           -0.2814,  0.2207, -0.0302, -0.1498, -0.3188, -0.0169]]],


        [[[ 0.1216, -0.0640, -0.1142, -0.1368, -0.2694, -0.168

3. Using GRUCell vs GRU for one2many/vec2seq architecture

In [4]:
torch.manual_seed(12)

# (features=4, hiddenlayer1=20)
rnn1 = nn.GRUCell(4, 20)
# (hiddenlayer1=20, hiddenlayer2=20)
rnn2 = nn.GRUCell(20, 20)
# (hiddenlayer2=20, output=20)
linear = nn.Linear(20,4)
# 2 batches, 4 features (input_v: "first input, 1 time step")
input_v = torch.randn(2, 4)
# batch, hidden size
hx1 = torch.zeros(2, 20)
# batch, hidden size
hx2 = torch.zeros(2, 20)
outputs = []
# appends first input
outputs += [input_v]
# loop "2 time steps"
for i in range(2):    
    # input to hidden 1
    hx1 = rnn1(input_v, hx1)   
    # hidden 1 to hidden 2
    hx2 = rnn2(hx1, hx2) 
    # hidden 2 to linear
    output = linear(hx2)
    # appends output
    outputs += [output]
    # set next input equals to the last output
    input_v = output

outputs  = torch.stack(outputs, dim = 0)

In [5]:
outputs

tensor([[[ 0.0838, -0.9325,  0.9319, -1.3625],
         [-0.5753,  1.5154,  1.2355, -0.6069]],

        [[ 0.1156,  0.2244,  0.1560, -0.0310],
         [ 0.0797,  0.2490,  0.1425, -0.0276]],

        [[ 0.1024,  0.2254,  0.1240, -0.0450],
         [ 0.0726,  0.2500,  0.1123, -0.0432]]], grad_fn=<StackBackward>)

In [6]:
torch.manual_seed(12)

# features, hidden size, layers (important 2 layers!)
rnn12 = nn.GRU(4, 20, 2)
# hidden size, output
linear = nn.Linear(20,4)

# 2 batches, 4 features
input_v = torch.randn(1, 2, 4)
# batch, hidden size
hx = torch.zeros(2, 2, 20)

outputs = []
# appends first input
outputs += [input_v]
# loop "2 time steps"
for i in range(2):    
    output, hidden = rnn12(input_v, hx) 
    output = linear(output)
    outputs += [output]
    input_v = output
    hx = hidden

outputs  = torch.stack(outputs, dim = 0)

In [7]:
outputs

tensor([[[[ 0.0838, -0.9325,  0.9319, -1.3625],
          [-0.5753,  1.5154,  1.2355, -0.6069]]],


        [[[ 0.1156,  0.2244,  0.1560, -0.0310],
          [ 0.0797,  0.2490,  0.1425, -0.0276]]],


        [[[ 0.1024,  0.2254,  0.1240, -0.0450],
          [ 0.0726,  0.2500,  0.1123, -0.0432]]]], grad_fn=<StackBackward>)